version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=registration
    ports:
      - 8080:8080
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

